### ISSUE TITLE
Migrate existing policies to Artifact Hub

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-hub#190]
Artifact Hub can now be used to list Kubewarden policies. We would like to publish all the policies that currently are on the Policy Hub over to Artifact Hub.

## Things to do

* [x] Migrate policies:  https://github.com/kubewarden/policy-hub/issues/195
* [x] Update the policy templates
  * [x] gatekeeper-policy-template
  * [x] go-policy-template
  * [x] opa-policy-template
  * [x] policy-rust-template
  * [x] swift-policy-template
* [x] Update the docs: https://github.com/kubewarden/docs/pull/134
* [x] Blog post: https://github.com/kubewarden/kubewarden.io/pull/118
* [x] #191
* [x] Reach out to Artifact Hub developers: ask if there's a way to show which policies have a container image signed via Sigstore. There's already something similar done for container images. See for example [this container image](https://artifacthub.io/packages/container/goreleaser/goreleaser), which has a "signed" badge next to its name -> **DONE** with https://github.com/artifacthub/hub/issues/2146

## Acceptance criteria

When migrating a policy to Artifact Hub, we will use the simple repo layout like [this one](https://github.com/tegioz/capabilities-psp-policy). There's going to be only a `artifacthub-pkg.yml` file inside of the root of the project.

Each repository should also have a [artifacthub-repo.yml](https://github.com/flavio/allowed-fsgroups-psp-policy/blob/main/artifact-hub/artifacthub-repo.yml) file inside of the root of the project. In this way the entry will be listed as "verified" by Artifact Hub UI.

**Comment by flavio** [comment]
This can be closed now
