### ISSUE TITLE
Epic: port PSP policies to Kubewarden

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-hub#32]
This is an epic that keeps track of porting the missing PSP policies to Kubewarden.

Currently, mutating admission policies cannot be done with tinygo, yet they can be done using rust or swift.

## To implement

Polices are sorted by decreasing priority:

* [x] [host namespaces](https://github.com/kubewarden/policy-hub/issues/23)
* [x] [sysctl](https://github.com/kubewarden/policy-hub/issues/31)
* [x] [allowed host paths](https://github.com/kubewarden/policy-hub/issues/26)
* [x] [user and groups](https://github.com/kubewarden/policy-hub/issues/28)
* [x] [selinux](https://github.com/kubewarden/policy-hub/issues/29)
* [x] [volumes](https://github.com/kubewarden/policy-hub/issues/24)
* [x] [fsgroups](https://github.com/kubewarden/policy-hub/issues/25)
* [x] [allowed proc mount types](https://github.com/kubewarden/policy-hub/issues/30)
* [x] [flex volume](https://github.com/kubewarden/policy-hub/issues/27)
* [x] [readonly root filesystem](https://github.com/kubewarden/policy-hub/issues/32)

## To extend

* [x] [default allow privilege escalation](https://github.com/kubewarden/allow-privilege-escalation-psp-policy/issues/7)

**Comment by ereslibre** [comment]
This is now done. I am going to double check that we have implemented all PSP's in the different splitted policies.

**Comment by flavio** [comment]
I've compared what we have with [this exhaustive list](https://github.com/appvia/psp-migration).

* [x] [privileged](https://github.com/appvia/psp-migration/tree/main/tests/privileged/psp.yaml)
* [x] [hostPID](https://github.com/appvia/psp-migration/tree/main/tests/hostPID/psp.yaml)
* [x] [hostIPC](https://github.com/appvia/psp-migration/tree/main/tests/hostIPC/psp.yaml)
* [x] [hostNetwork](https://github.com/appvia/psp-migration/tree/main/tests/hostNetwork/psp.yaml)
* [x] [hostPorts](https://github.com/appvia/psp-migration/tree/main/tests/hostPorts/psp.yaml)
* [x] [volumes](https://github.com/appvia/psp-migration/tree/main/tests/volumes/psp.yaml)
* [x] [allowedHostPaths](https://github.com/appvia/psp-migration/tree/main/tests/allowedHostPaths/psp.yaml)
* [x] [allowedFlexVolumes](https://github.com/appvia/psp-migration/tree/main/tests/allowedFlexVolumes/psp.yaml)
* [ ] [readOnlyRootFilesystem](https://github.com/appvia/psp-migration/tree/main/tests/readOnlyRootFilesystem/psp.yaml)
* [x] [runAsUser](https://github.com/appvia/psp-migration/tree/main/tests/runAsUser/psp.yaml)
* [x] [runAsGroup](https://github.com/appvia/psp-migration/tree/main/tests/runAsGroup/psp.yaml)
* [x] [supplementalGroups](https://github.com/appvia/psp-migration/tree/main/tests/supplementalGroups/psp.yaml)
* [x] [fsgroup](https://github.com/appvia/psp-migration/tree/main/tests/fsgroup/psp.yaml)
* [x] [allowPrivilegeEscalation](https://github.com/appvia/psp-migration/tree/main/tests/allowPrivilegeEscalation/psp.yaml)
* [ ] [defaultAllowPrivilegeEscalation](https://github.com/appvia/psp-migration/tree/main/tests/defaultAllowPrivilegeEscalation/psp.yaml)
* [x] [allowedCapabilities](https://github.com/appvia/psp-migration/tree/main/tests/allowedCapabilities/psp.yaml)
* [x] [defaultAddCapabilities](https://github.com/appvia/psp-migration/tree/main/tests/defaultAddCapabilities/psp.yaml)
* [x] [requiredDropCapabilities](https://github.com/appvia/psp-migration/tree/main/tests/requiredDropCapabilities/psp.yaml)
* [x] [seLinux](https://github.com/appvia/psp-migration/tree/main/tests/seLinux/psp.yaml)
* [x] [allowedProcMountTypes](https://github.com/appvia/psp-migration/tree/main/tests/allowedProcMountTypes/psp.yaml)
* [x] [apparmor](https://github.com/appvia/psp-migration/tree/main/tests/apparmor/psp.yaml)
* [x] [seccomp](https://github.com/appvia/psp-migration/tree/main/tests/seccomp/psp.yaml)
* [x] [forbiddenSysctls](https://github.com/appvia/psp-migration/tree/main/tests/forbiddenSysctls/psp.yaml)
* [x] [allowedUnsafeSysctls](https://github.com/appvia/psp-migration/tree/main/tests/allowedUnsafeSysctls/psp.yaml)


It looks like we have to implement only two policies: the `readOnlyRootFilesystem` and the `defaultAllowPrivilegeEscalation`. In some cases I think we can solve that by extending one of the already existing policies we have. I'll file dedicated issues for that

**Comment by ereslibre** [comment]
Sigh, sorry for not doing this. And thanks for having checked.

**Comment by jvanz** [comment]
@flavio don't we miss the seccomp policy as well? We have the policy to check the annotation, but should not we have the policy to verify the request's `securityContext` ?

**Comment by ereslibre** [comment]
Yes, we are missing seccomp.

**Comment by flavio** [comment]
@jvanz yes, please file a dedicated issue inside of the policy-hub repo, then start working on that as we discussed during the daily :+1: :pray:

**Comment by ereslibre** [comment]
This is now completed 🎉
